### ISSUE TITLE
Let's combine efforts! if you like?

### ISSUE THREAD

**Issue by webbertakken** [pCYSl5EDgo/setup-unity#1]
Hi @pCYSl5EDgo,

Awesome work on your repo! I see you're going with the approach to setting up Unity in the main container of your workflow. I have thought about doing the same but ended up splitting up into separate actions, because  the build step may require several specialised docker images.

I have gotten the first part (request activation, activate and test) entirely completed and documented and was wondering whether you feel like combining our efforts?

I have listed my actions here, themed  "[Unity Actions](https://github.com/webbertakken/unity-actions)" and would love to maybe work together if you would be up for it. 

Perhaps we should support both single container as action based workflows. Let me know what you think.

**Comment by pCYSl5EDgo** [comment]
It's a good idea to split Unity workflows(CreateManualActivationFile, Testing, Building, ExecuteMethod) into separate actions.

I respect gableroux's great docker containers.
There are a few disadvantages in gableroux/unity3d.
1: Doesn't provide programmers with beta/alpha version Unity.
2: Doesn't let programmers 'sudo'.
3: Can't build IL2CPP with gableroux/unity3d.

To solve those problems, I made this GitHub Action.
I don't need to maintain this action to catch up the latest Unity version.

As long as using gableroux/unity3d docker containers, The GitHub Action owner should be worried about Unity version problem.
I have no motivation to make new Docker GitHub Actions relating to gableroux/unity3d.

Let me know what you want me to do.

**Comment by webbertakken** [comment]
Hi @pCYSl5EDgo,

> I respect gableroux's great docker containers.
> There are a few disadvantages in gableroux/unity3d.
> 1: Doesn't provide programmers with beta/alpha version Unity.
> 2: Doesn't let programmers 'sudo'.
> 3: Can't build IL2CPP with gableroux/unity3d.
> 
> To solve those problems, I made this GitHub Action.

I'm open to solve these problems in my actions as well. My approach would be to pre-package the different requirements per platform in separate container images and simply pull the container of the desired version and type based on the action's configuration. 

We could build these containers automatically whenever a new version of unity releases. That way it's possible to leverage caching for some heavy lifting. 

I think this would solve all the challenges you mentioned above;

- No more worrying about Unity version problem, including alpha/beta versions
- We could support IL2CPP

> I have no motivation to make new Docker GitHub Actions relating to gableroux/unity3d.
> 
> Let me know what you want me to do.

I found that builds can take a rather long time to finish. For this reason I didn't go for a single-runner flow, but rather distributed in separate actions. That way build steps can run in parallel. 

I'm curious; it is possible to run the builds for all platforms in parallel? And if so, how does that work?

If not; perhaps we could combine efforts by using your logic to create the docker images and my actions to run on top of it. Let me know what you think

**Comment by pCYSl5EDgo** [comment]
It seems that parallel per-platform Unity Build can be achived manually by spliting jobs.
[This is an example of parallel 20 tests.](https://github.com/pCYSl5EDgo/UniNativeLinq-EditorExtension-Test/commit/7607cfa1308de83428b4111a22324c22bc288667/checks?check_suite_id=252559356)

I have no idea to make Unity run parallel in one job or in a Github Action.
"strategy.matrix" of GitHub Actions might be a help to this problem.

>It might be necessary to have another repository automatically generate images for each version of Unity

I agree with you.

**Comment by webbertakken** [comment]
> It seems that parallel per-platform Unity Build can be achived manually by spliting jobs.

Ah yes that could work. However that would run every prerequisite step as well for every job. 

This is what I'm currently trying to prevent. 

I'm curious whether there will be solutions where you could setup a container and then split actions from there. In that case, the setup job would certainly allow a lot of customisation for sure.

**Comment by pCYSl5EDgo** [comment]
Hmm...
How about installing two same version Unity Editors on different location such as /opt/Unity-0 and /opt/Unity-1? (This is because GitHub Actions virtual environment provides only two threads.)
Then create two threads or child processes to run Unity separately.

**Comment by webbertakken** [comment]
It could work, however I do worry about the scalability of that solution.

One downside is that it would make the action even less portable, whereas Actions may evolve to also run locally. This may not be so easy with specific implementations like finding out how many threads a machine has and then distributing different versions of unity between threads.

Another downside is that it doesn't allow for multi-threading optimisations.

Containers solve both downsides as they can be easily distributed to k8s clusters; other CI systems already do this, I would expect Github to also make great optimisations over time, including caching and distribution.

**Comment by pCYSl5EDgo** [comment]
Prallel Unity Build with scalability is difficult...

Okay, container technology is great.

It would be nice to make new repository which checks UnityCsReference everyday and publish docker containers.
Unity Technologies' commit comments are very systematic.
'Unity 2020.1.0a11 C# reference source code'
'Unity 2020.1.0a9 C# reference source code'
With some regex, new Unity version can be detected.

It seems to be not so difficult.

**Comment by pCYSl5EDgo** [comment]
Oh, I've missed one reason why I made 'unity-setup'!
I need Unity's DLL in my GitHub Action jobs to build managed plugins.
[UniEnumExtension](https://github.com/pCYSl5EDgo/UniEnumExtension) & [It's build repository](https://github.com/pCYSl5EDgo/UniEnumExtension-Builder).
[UniNativeLinq](https://github.com/pCYSl5EDgo/UniNativeLinq-EditorExtension) & [it's test and build repository](https://github.com/pCYSl5EDgo/UniNativeLinq-EditorExtension-Test).

**Comment by pCYSl5EDgo** [comment]
https://github.com/pCYSl5EDgo/unity-license-activate

Above Repository provides the way to create ulf file from alf.
